### ISSUE TITLE
Streamlit chat bot pack download error (max retries)

### ISSUE THREAD

**Issue by abhinavkala** [carolinedlu/llamaindex-chat-with-streamlit-docs#5]
I am facing this error while downloading the Streamlit chatbot pack,please help:

```
(venv) PS C:\Users\Testbook\OneDrive\Desktop\Streamlit\venv\Scripts> llamaindex-cli download-llamapack StreamlitChatPack --download-dir ./streamlit_chatbot_pack
Traceback (most recent call last):
  File "C:\Users\Testbook\OneDrive\Desktop\Streamlit\venv\Lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Testbook\OneDrive\Desktop\Streamlit\venv\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "C:\Users\Testbook\OneDrive\Desktop\Streamlit\venv\Lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Testbook\OneDrive\Desktop\Streamlit\venv\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Testbook\OneDrive\Desktop\Streamlit\venv\Lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "C:\Users\Testbook\OneDrive\Desktop\Streamlit\venv\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Testbook\OneDrive\Desktop\Streamlit\venv\Lib\site-packages\urllib3\connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "C:\Users\Testbook\OneDrive\Desktop\Streamlit\venv\Lib\site-packages\urllib3\connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\Testbook\OneDrive\Desktop\Streamlit\venv\Lib\site-packages\urllib3\connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x000001B749585510>, 'Connection to raw.githubusercontent.com timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Testbook\OneDrive\Desktop\Streamlit\venv\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Testbook\OneDrive\Desktop\Streamlit\venv\Lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Testbook\OneDrive\Desktop\Streamlit\venv\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /run-llama/llama-hub/main/llama_hub/llama_packs/library.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001B749585510>, 'Connection to raw.githubusercontent.com timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Testbook\OneDrive\Desktop\Streamlit\venv\Scripts\llamaindex-cli.exe\__main__.py", line 7, in <module>
  File "C:\Users\Testbook\OneDrive\Desktop\Streamlit\venv\Lib\site-packages\llama_index\command_line\command_line.py", line 125, in main
    args.func(args)
  File "C:\Users\Testbook\OneDrive\Desktop\Streamlit\venv\Lib\site-packages\llama_index\command_line\command_line.py", line 83, in <lambda>
    func=lambda args: handle_download_llama_pack(**vars(args))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Testbook\OneDrive\Desktop\Streamlit\venv\Lib\site-packages\llama_index\command_line\command_line.py", line 21, in handle_download_llama_pack
    download_llama_pack(
  File "C:\Users\Testbook\OneDrive\Desktop\Streamlit\venv\Lib\site-packages\llama_index\llama_pack\download.py", line 29, in download_llama_pack
    pack_cls = download_llama_module(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Testbook\OneDrive\Desktop\Streamlit\venv\Lib\site-packages\llama_index\download\module.py", line 216, in download_llama_module
    module_info = get_module_info(
                  ^^^^^^^^^^^^^^^^
  File "C:\Users\Testbook\OneDrive\Desktop\Streamlit\venv\Lib\site-packages\llama_index\download\module.py", line 66, in get_module_info
    library_raw_content, _ = get_file_content(
                             ^^^^^^^^^^^^^^^^^
  File "C:\Users\Testbook\OneDrive\Desktop\Streamlit\venv\Lib\site-packages\llama_index\download\utils.py", line 10, in get_file_content
    resp = requests.get(url + path)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Testbook\OneDrive\Desktop\Streamlit\venv\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Testbook\OneDrive\Desktop\Streamlit\venv\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Testbook\OneDrive\Desktop\Streamlit\venv\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Testbook\OneDrive\Desktop\Streamlit\venv\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Testbook\OneDrive\Desktop\Streamlit\venv\Lib\site-packages\requests\adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /run-llama/llama-hub/main/llama_hub/llama_packs/library.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001B749585510>, 'Connection to raw.githubusercontent.com timed out. (connect timeout=None)'))
```

**Comment by abhinavkala** [comment]
i used a different internet connection
